@baseUrl = http://localhost:3000
#@baseUrl = https://notes-db-5hb8.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInVzZXJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3OTAyNjYwMjgsImV4cCI6MTc5Mjg1ODAyOH0.8DA5YJttdUnoScQhGVtL1q6nW1LfbKy2MFcsA-jw808


GET {{baseUrl}}/boards
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/boards/4/notes
Authorization: Bearer {{token}}
###
POST {{baseUrl}}/boards
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Project B",
    "allowed_users": [4, 9, 2]
}
###
PUT {{baseUrl}}/boards/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Project A - renamed",
    "allowed_users": [1, 4]
}
###
PATCH {{baseUrl}}/boards/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "allowed_users": [6, 1, 15]
}
###
DELETE {{baseUrl}}/boards/3
Authorization: Bearer {{token}}
###

GET {{baseUrl}}/notes
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/notes/3
Authorization: Bearer {{token}}
###

POST {{baseUrl}}/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "note": "test note 3",
    "board_id": 1
}
###

POST {{baseUrl}}/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "note": "note with location",
    "board_id": 1,
    "location": { "x": 200, "y": 150 }
}
###
PUT {{baseUrl}}/notes/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "author_id": 1,
    "note": "updated note",
    "board_id": 1
}

###
PATCH {{baseUrl}}/notes/11
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "note": "letsgo"
}

###

PATCH {{baseUrl}}/notes/15
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "location": { "x": 120, "y": 340 }
}

###

PATCH {{baseUrl}}/notes/18
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "note": "moved and edited",
    "location": { "x": 50, "y": 75 }
}

###

PATCH {{baseUrl}}/notes/11
Authorization: Bearer {{token}}
Content-Type: application/json

{}

###

DELETE {{baseUrl}}/notes/3
Authorization: Bearer {{token}}
